# 标准化 

In [32]:
from sklearn.preprocessing import StandardScaler

In [33]:
s = StandardScaler()

In [34]:
s.fit_transform([[1,2,3],[4,5,6]])

array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])

In [35]:
s.fit([[1,2,3],[4,5,6]])

StandardScaler(copy=True, with_mean=True, with_std=True)

In [36]:
s.transform([[1,2,3],[4,5,6]])

array([[-1., -1., -1.],
       [ 1.,  1.,  1.]])

In [39]:
s.fit([[2,3,4],[4,5,7]])

StandardScaler(copy=True, with_mean=True, with_std=True)

In [40]:
s.transform([[1,2,3],[4,5,6]])

array([[-2.        , -2.        , -1.66666667],
       [ 1.        ,  1.        ,  0.33333333]])

---  
---
---

---  
---
---

---  
---
---

In [7]:
import pandas as pd

# 朴素贝叶斯
>- 分类准确率高，速度快
>- 不需要调参  

>- 样本属性有关联时效果不好


In [1]:
from sklearn.datasets import fetch_20newsgroups
news = fetch_20newsgroups(data_home=r'F:\Jupyter notebook\data')

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [31]:
for i in news.data[:3]:
    print(i, '*'*100)

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----




 ****************************************************************************************************
From: guykuo@carson.u.washington.edu (Guy Kuo)
Subject: SI Clock Poll - Final Call
Summary: Final call for SI clock reports
Keywords: SI,acceleration,clock,upgrade
Article-I.D.:

In [30]:
news.target

array([7, 4, 4, ..., 3, 1, 8])

In [9]:
news.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [5]:
x_train, x_test, y_train, y_test = train_test_split(news.data, news.target, test_size=0.25)

# 对数据集进行特征抽取
tf = TfidfVectorizer()

# 以训练集当中的词的列表进行每篇文章重要性统计['a','b','c','d']
x_train = tf.fit_transform(x_train)
x_test = tf.transform(x_test)

print(tf.get_feature_names()[:10])

# 进行朴素贝叶斯算法的预测
mlt = MultinomialNB(alpha=0.1)  # 每个分母+1.0   [(6+1)/100][(0+1)/100][...]

print(x_train.toarray()[:10])

mlt.fit(x_train, y_train)

y_predict = mlt.predict(x_test)

print("预测的文章类别为：", y_predict[:10])

# 得出准确率
print("准确率为：", mlt.score(x_test, y_test))

print("每个类别的精确率和召回率：\n", classification_report(y_test, y_predict, target_names=news.target_names))

['00', '000', '0000', '00000', '000000', '00000000', '0000000004', '0000000005', '00000000b', '00000001']
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
预测的文章类别为： [11  7 15 11  7 12 12  5 15 14]
准确率为： 0.9003181336161188
每个类别的精确率和召回率：
                           precision    recall  f1-score   support

             alt.atheism       0.95      0.90      0.92       124
           comp.graphics       0.88      0.86      0.87       154
 comp.os.ms-windows.misc       0.86      0.84      0.85       134
comp.sys.ibm.pc.hardware       0.81      0.84      0.82       158
   comp.sys.mac.hardware       0.85      0.87      0.86       148
          comp.windows.x       0.92      0.89      0.90       157
            misc.forsale       0.90      0.73      0.81       128
               rec.autos       0.91      0.92      0.91       153
         rec.motorcycles       0.97      0.95      0.96      

---  
---
---

# 决策树
>- 认识决策树   
>- 信息论基础-银行贷款分析   
>- 决策树的生成   
>- 泰坦尼克号乘客生存分类   

>### 决策树对泰坦尼克号进行预测生死

In [8]:
df = pd.read_csv('http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic.txt')
df.head()

row.names pclass  survived  \
0          1    1st         1   
1          2    1st         0   
2          3    1st         0   
3          4    1st         0   
4          5    1st         1   

                                              name      age     embarked  \
0                     Allen, Miss Elisabeth Walton  29.0000  Southampton   
1                      Allison, Miss Helen Loraine   2.0000  Southampton   
2              Allison, Mr Hudson Joshua Creighton  30.0000  Southampton   
3  Allison, Mrs Hudson J.C. (Bessie Waldo Daniels)  25.0000  Southampton   
4                    Allison, Master Hudson Trevor   0.9167  Southampton   

                         home.dest room      ticket   boat     sex  
0                     St Louis, MO  B-5  24160 L221      2  female  
1  Montreal, PQ / Chesterville, ON  C26         NaN    NaN  female  
2  Montreal, PQ / Chesterville, ON  C26         NaN  (135)    male  
3  Montreal, PQ / Chesterville, ON  C26         NaN    NaN  female  
4  Montreal, PQ / Chesterville, ON  C22         NaN     11    male

In [17]:
# 处理数据，找出特征值和目标值
x = df[['pclass', 'age', 'sex']]
y = df['survived']

# 缺失值处理
x['age'].fillna(x['age'].mean(), inplace=True)
print(x.head(),y.head(10))

# 分割数据集到训练集合测试集
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

# 进行处理(特征工程)特征->类别->one_hot编码
from sklearn.feature_extraction import DictVectorizer
dic = DictVectorizer(sparse=False)

x_train = dic.fit_transform(x_train.to_dict(orient='records'))  # 把一行转换为一个dict
print(dic.get_feature_names())

x_test = dic.transform(x_test.to_dict(orient='records'))

print(x_train)

  pclass      age     sex
0    1st  29.0000  female
1    1st   2.0000  female
2    1st  30.0000    male
3    1st  25.0000  female
4    1st   0.9167    male 0    1
1    0
2    0
3    0
4    1
5    1
6    1
7    0
8    1
9    0
Name: survived, dtype: int64
['age', 'pclass=1st', 'pclass=2nd', 'pclass=3rd', 'sex=female', 'sex=male']
[[ 3.          0.          0.          1.          0.          1.        ]
 [31.19418104  0.          1.          0.          0.          1.        ]
 [36.          1.          0.          0.          0.          1.        ]
 ...
 [32.          0.          1.          0.          1.          0.        ]
 [36.          1.          0.          0.          0.          1.        ]
 [31.19418104  0.          0.          1.          0.          1.        ]]


E:\Anaconda\lib\site-packages\pandas\core\generic.py:5430: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [18]:
from sklearn.tree import DecisionTreeClassifier, export_graphviz

dec = DecisionTreeClassifier(max_depth=5)  # max_depth=5

dec.fit(x_train, y_train)

print('预测的准确率:', dec.score(x_test, y_test))

预测的准确率: 0.8358662613981763


In [15]:
# 导出决策树的结构
export_graphviz(dec, out_file="./tree.dot",
                feature_names=['年龄', 'pclass=1st', 'pclass=2nd',
                               'pclass=3rd', '女性', '男性']
               )

# dot -Tpng tree.dot -o tree.png

---  
---
---

# 集成学习方法
> 集成学习通过建立几个模型组合的来解决单一预测问题。它的工作原理是生成多个分类器/模型，各自独立地学习和作出预测。这些预测最后结合成单预测，因此优于任何一个单分类的做出预测.

# 随机森林
> 在机器学习中，随机森林是一个包含多个决策树的分类器，并且其输出的类别是由个别树输出的类别的众数而定.

> class sklearn.ensemble.RandomForestClassifier(n_estimators=10, criterion='gini',max_depth=None, bootstrap=True, random_state=None)   
- 随机森林分类器   
- n_estimators：integer，optional(default = 10) 森林里的树木数量   
- criteria：string，可选(default ='gini')分割特征的测量方法   
- max_depth：integer或None，可选(默认=无)树的最大深度    
- bootstrap：boolean，optional(default = True)是否在构建树时使用放回抽样 

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [19]:
rf = RandomForestClassifier() # n_estimators=, max_depth=
param = {'n_estimators':[120, 200, 300, 500, 800, 1200], 'max_depth':[5, 8, 15, 25, 30]}

# 网格搜索与交叉验证
gc = GridSearchCV(rf, param_grid=param, cv=2)
gc.fit(x_train, y_train)

print("准确率：", gc.score(x_test, y_test))
print("查看选择的参数模型：", gc.best_params_)

准确率： 0.8389057750759878
查看选择的参数模型： {'max_depth': 5, 'n_estimators': 120}


>1. 在当前所有算法中，具有极好的准确率
>2. 能够有效地运行在大数据集上
>3. 能够处理具有高维特征的输入样本，而且不需要降维
>4. 能够评估各个特征在分类问题上的重要性
>5. 对于缺省值问题也能够获得很好得结果