In [1]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from tensorflow.contrib.slim.python.slim.nets.inception_v3 import inception_v3

|算法| 策略 | 优化|
|---|---|---|
|线性回归|均方误差|梯度下降|
|逻辑回归|对数似然损失|梯度下降/二分类|
|神经网络|交叉熵损失|反向传播算法(梯度下降)|

--- 
---
---

# Mnist数据集神经网络分析

In [3]:
from tensorflow.examples.tutorials.mnist import input_data

In [5]:
mnist = input_data.read_data_sets('./data/', one_hot=True)

Extracting ./data/train-images-idx3-ubyte.gz
Extracting ./data/train-labels-idx1-ubyte.gz
Extracting ./data/t10k-images-idx3-ubyte.gz
Extracting ./data/t10k-labels-idx1-ubyte.gz


In [25]:
len(mnist.train.images)

55000

In [13]:
mnist.train.images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [19]:
mnist.train.images[0] # 784个

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [22]:
mnist.train.labels[:20]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
mnist.train.next_batch(20)

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.,

In [54]:
def full_connected():
    with tf.variable_scope('data'):
        x = tf.placeholder(tf.float32, [None, 784])
        
        y_true = tf.placeholder(tf.int32, [None, 10])
        
    with tf.variable_scope('fc_model'): 
        weight = tf.Variable(tf.random_normal([784, 10], mean=0.0, stddev=1.0), name='w')
        
        bias = tf.Variable(tf.constant(0.0, shape=[10]))
        
        y_predict = tf.matmul(x, weight) + bias
        
    with tf.variable_scope('soft_cross'): 
        loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_true, logits=y_predict))
        
    with tf.variable_scope('optimizer'): 
        train_op = tf.train.GradientDescentOptimizer(0.1).minimize(loss)
        
    with tf.variable_scope('acc'):
        equal_list = tf.equal(tf.argmax(y_true, 1), tf.argmax(y_predict, 1))
        
        accuracy = tf.reduce_mean(tf.cast(equal_list, tf.float32))
    
#     tf.summary.scalar('losses', loss)
#     tf.summary.scalar('acc', accuracy)
    
#     tf.summary.histogram('weights', weight)
#     tf.summary.histogram('bias', bias)
    
    init_op = tf.global_variables_initializer()
    
    merged = tf.summary.merge_all()
    
    with tf.Session() as sess:
        sess.run(init_op)
        
        filewriter = tf.summary.FileWriter('./temp/', graph=sess.graph)
        
        for i in range(2000):
            mnist_x, mnist_y = mnist.train.next_batch(50)
            
#             mnist_y = mnist_y.astype('int32')
                        
            sess.run(train_op, feed_dict={
                x:mnist_x,
                y_true:mnist_y
            })
            
#             summary = sess.run(merged, feed_dict={
#                 x: mnist_x,
#                 y_true: mnist_y
#             })
#             filewriter.add_summary(summary, i)
            
            print('训练{}次, 准确率为{}.'.format(i, sess.run(accuracy, feed_dict={
                 x:mnist_x,
                 y_true:mnist_y
            })))
            
        
full_connected()

训练0次, 准确率为0.10000000149011612.
训练1次, 准确率为0.2199999988079071.
训练2次, 准确率为0.14000000059604645.
训练3次, 准确率为0.11999999731779099.
训练4次, 准确率为0.019999999552965164.
训练5次, 准确率为0.20000000298023224.
训练6次, 准确率为0.11999999731779099.
训练7次, 准确率为0.05999999865889549.
训练8次, 准确率为0.1599999964237213.
训练9次, 准确率为0.07999999821186066.
训练10次, 准确率为0.1599999964237213.
训练11次, 准确率为0.11999999731779099.
训练12次, 准确率为0.11999999731779099.
训练13次, 准确率为0.03999999910593033.
训练14次, 准确率为0.20000000298023224.
训练15次, 准确率为0.18000000715255737.
训练16次, 准确率为0.14000000059604645.
训练17次, 准确率为0.14000000059604645.
训练18次, 准确率为0.2199999988079071.
训练19次, 准确率为0.18000000715255737.
训练20次, 准确率为0.14000000059604645.
训练21次, 准确率为0.1599999964237213.
训练22次, 准确率为0.2199999988079071.
训练23次, 准确率为0.11999999731779099.
训练24次, 准确率为0.18000000715255737.
训练25次, 准确率为0.18000000715255737.
训练26次, 准确率为0.11999999731779099.
训练27次, 准确率为0.2199999988079071.
训练28次, 准确率为0.10000000149011612.
训练29次, 准确率为0.2199999988079071.
训练30次, 准确率为0.20000000298023224.
训练31次, 准确率为0.180000007152

训练353次, 准确率为0.7200000286102295.
训练354次, 准确率为0.699999988079071.
训练355次, 准确率为0.800000011920929.
训练356次, 准确率为0.6800000071525574.
训练357次, 准确率为0.6600000262260437.
训练358次, 准确率为0.699999988079071.
训练359次, 准确率为0.5199999809265137.
训练360次, 准确率为0.6600000262260437.
训练361次, 准确率为0.6399999856948853.
训练362次, 准确率为0.699999988079071.
训练363次, 准确率为0.6399999856948853.
训练364次, 准确率为0.6800000071525574.
训练365次, 准确率为0.6600000262260437.
训练366次, 准确率为0.6000000238418579.
训练367次, 准确率为0.7799999713897705.
训练368次, 准确率为0.7200000286102295.
训练369次, 准确率为0.6800000071525574.
训练370次, 准确率为0.6800000071525574.
训练371次, 准确率为0.6399999856948853.
训练372次, 准确率为0.7200000286102295.
训练373次, 准确率为0.6800000071525574.
训练374次, 准确率为0.7400000095367432.
训练375次, 准确率为0.7799999713897705.
训练376次, 准确率为0.6800000071525574.
训练377次, 准确率为0.7799999713897705.
训练378次, 准确率为0.7400000095367432.
训练379次, 准确率为0.800000011920929.
训练380次, 准确率为0.7599999904632568.
训练381次, 准确率为0.6600000262260437.
训练382次, 准确率为0.699999988079071.
训练383次, 准确率为0.7400000095367432.
训练384次, 准确率为0.

训练614次, 准确率为0.6399999856948853.
训练615次, 准确率为0.7599999904632568.
训练616次, 准确率为0.7599999904632568.
训练617次, 准确率为0.699999988079071.
训练618次, 准确率为0.7599999904632568.
训练619次, 准确率为0.8399999737739563.
训练620次, 准确率为0.699999988079071.
训练621次, 准确率为0.7200000286102295.
训练622次, 准确率为0.7599999904632568.
训练623次, 准确率为0.8600000143051147.
训练624次, 准确率为0.7799999713897705.
训练625次, 准确率为0.699999988079071.
训练626次, 准确率为0.7799999713897705.
训练627次, 准确率为0.6399999856948853.
训练628次, 准确率为0.8399999737739563.
训练629次, 准确率为0.5799999833106995.
训练630次, 准确率为0.7400000095367432.
训练631次, 准确率为0.7799999713897705.
训练632次, 准确率为0.800000011920929.
训练633次, 准确率为0.7799999713897705.
训练634次, 准确率为0.699999988079071.
训练635次, 准确率为0.8600000143051147.
训练636次, 准确率为0.7400000095367432.
训练637次, 准确率为0.7400000095367432.
训练638次, 准确率为0.7400000095367432.
训练639次, 准确率为0.7200000286102295.
训练640次, 准确率为0.699999988079071.
训练641次, 准确率为0.800000011920929.
训练642次, 准确率为0.7200000286102295.
训练643次, 准确率为0.7400000095367432.
训练644次, 准确率为0.7400000095367432.
训练645次, 准确率为0.7

训练890次, 准确率为0.7200000286102295.
训练891次, 准确率为0.8799999952316284.
训练892次, 准确率为0.8600000143051147.
训练893次, 准确率为0.8799999952316284.
训练894次, 准确率为0.7200000286102295.
训练895次, 准确率为0.7400000095367432.
训练896次, 准确率为0.8600000143051147.
训练897次, 准确率为0.800000011920929.
训练898次, 准确率为0.800000011920929.
训练899次, 准确率为0.8199999928474426.
训练900次, 准确率为0.7799999713897705.
训练901次, 准确率为0.8399999737739563.
训练902次, 准确率为0.7400000095367432.
训练903次, 准确率为0.7799999713897705.
训练904次, 准确率为0.7599999904632568.
训练905次, 准确率为0.8199999928474426.
训练906次, 准确率为0.7200000286102295.
训练907次, 准确率为0.9200000166893005.
训练908次, 准确率为0.800000011920929.
训练909次, 准确率为0.7200000286102295.
训练910次, 准确率为0.8199999928474426.
训练911次, 准确率为0.699999988079071.
训练912次, 准确率为0.8199999928474426.
训练913次, 准确率为0.7400000095367432.
训练914次, 准确率为0.8199999928474426.
训练915次, 准确率为0.8799999952316284.
训练916次, 准确率为0.6600000262260437.
训练917次, 准确率为0.7799999713897705.
训练918次, 准确率为0.6200000047683716.
训练919次, 准确率为0.8600000143051147.
训练920次, 准确率为0.800000011920929.
训练921次, 准确率为0

训练1150次, 准确率为0.8799999952316284.
训练1151次, 准确率为0.8399999737739563.
训练1152次, 准确率为0.800000011920929.
训练1153次, 准确率为0.7400000095367432.
训练1154次, 准确率为0.7799999713897705.
训练1155次, 准确率为0.8399999737739563.
训练1156次, 准确率为0.8199999928474426.
训练1157次, 准确率为0.8399999737739563.
训练1158次, 准确率为0.7799999713897705.
训练1159次, 准确率为0.8399999737739563.
训练1160次, 准确率为0.7200000286102295.
训练1161次, 准确率为0.8199999928474426.
训练1162次, 准确率为0.8799999952316284.
训练1163次, 准确率为0.800000011920929.
训练1164次, 准确率为0.7400000095367432.
训练1165次, 准确率为0.7599999904632568.
训练1166次, 准确率为0.8600000143051147.
训练1167次, 准确率为0.7200000286102295.
训练1168次, 准确率为0.8199999928474426.
训练1169次, 准确率为0.800000011920929.
训练1170次, 准确率为0.8399999737739563.
训练1171次, 准确率为0.8399999737739563.
训练1172次, 准确率为0.8600000143051147.
训练1173次, 准确率为0.7799999713897705.
训练1174次, 准确率为0.800000011920929.
训练1175次, 准确率为0.8199999928474426.
训练1176次, 准确率为0.6800000071525574.
训练1177次, 准确率为0.8199999928474426.
训练1178次, 准确率为0.8199999928474426.
训练1179次, 准确率为0.7200000286102295.
训练1180次, 准确率为0

训练1424次, 准确率为0.800000011920929.
训练1425次, 准确率为0.8600000143051147.
训练1426次, 准确率为0.8999999761581421.
训练1427次, 准确率为0.8199999928474426.
训练1428次, 准确率为0.9200000166893005.
训练1429次, 准确率为0.8399999737739563.
训练1430次, 准确率为0.8199999928474426.
训练1431次, 准确率为0.8199999928474426.
训练1432次, 准确率为0.8199999928474426.
训练1433次, 准确率为0.7599999904632568.
训练1434次, 准确率为0.8199999928474426.
训练1435次, 准确率为0.8600000143051147.
训练1436次, 准确率为0.8600000143051147.
训练1437次, 准确率为0.8199999928474426.
训练1438次, 准确率为0.8799999952316284.
训练1439次, 准确率为0.8999999761581421.
训练1440次, 准确率为0.7799999713897705.
训练1441次, 准确率为0.8600000143051147.
训练1442次, 准确率为0.8600000143051147.
训练1443次, 准确率为0.7799999713897705.
训练1444次, 准确率为0.800000011920929.
训练1445次, 准确率为0.8600000143051147.
训练1446次, 准确率为0.9800000190734863.
训练1447次, 准确率为0.8600000143051147.
训练1448次, 准确率为0.8199999928474426.
训练1449次, 准确率为0.7400000095367432.
训练1450次, 准确率为0.8999999761581421.
训练1451次, 准确率为0.7799999713897705.
训练1452次, 准确率为0.8199999928474426.
训练1453次, 准确率为0.8199999928474426.
训练1454次, 准确率

训练1709次, 准确率为0.8600000143051147.
训练1710次, 准确率为0.8799999952316284.
训练1711次, 准确率为0.8600000143051147.
训练1712次, 准确率为0.8399999737739563.
训练1713次, 准确率为0.8199999928474426.
训练1714次, 准确率为0.7599999904632568.
训练1715次, 准确率为0.8600000143051147.
训练1716次, 准确率为0.8199999928474426.
训练1717次, 准确率为0.8399999737739563.
训练1718次, 准确率为0.9200000166893005.
训练1719次, 准确率为0.8399999737739563.
训练1720次, 准确率为0.8399999737739563.
训练1721次, 准确率为0.8600000143051147.
训练1722次, 准确率为0.8600000143051147.
训练1723次, 准确率为0.8799999952316284.
训练1724次, 准确率为0.8799999952316284.
训练1725次, 准确率为0.8799999952316284.
训练1726次, 准确率为0.7400000095367432.
训练1727次, 准确率为0.8199999928474426.
训练1728次, 准确率为0.800000011920929.
训练1729次, 准确率为0.9200000166893005.
训练1730次, 准确率为0.7799999713897705.
训练1731次, 准确率为0.8399999737739563.
训练1732次, 准确率为0.800000011920929.
训练1733次, 准确率为0.8399999737739563.
训练1734次, 准确率为0.8999999761581421.
训练1735次, 准确率为0.7200000286102295.
训练1736次, 准确率为0.8600000143051147.
训练1737次, 准确率为0.9599999785423279.
训练1738次, 准确率为0.8999999761581421.
训练1739次, 准确率

训练1998次, 准确率为0.8600000143051147.
训练1999次, 准确率为0.800000011920929.


In [ ]:
# FLAGS = tf.app.flags.FLAGS
# tf.app.flags.DEFINE_integer("is_train", 1, "指定程序是预测还是训练")

def full_connected():
    # 获取真实的数据
    mnist = input_data.read_data_sets("./data/mnist/input_data/", one_hot=True)

    # 1、建立数据的占位符 x [None, 784]    y_true [None, 10]
    with tf.variable_scope("data"):
        x = tf.placeholder(tf.float32, [None, 784])

        y_true = tf.placeholder(tf.int32, [None, 10])

    # 2、建立一个全连接层的神经网络 w [784, 10]   b [10]
    with tf.variable_scope("fc_model"):
        # 随机初始化权重和偏置
        weight = tf.Variable(tf.random_normal([784, 10], mean=0.0, stddev=1.0), name="w")

        bias = tf.Variable(tf.constant(0.0, shape=[10]))

        # 预测None个样本的输出结果matrix [None, 784]* [784, 10] + [10] = [None, 10]
        y_predict = tf.matmul(x, weight) + bias

    # 3、求出所有样本的损失，然后求平均值
    with tf.variable_scope("soft_cross"):

        # 求平均交叉熵损失
        loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y_true, logits=y_predict))

    # 4、梯度下降求出损失
    with tf.variable_scope("optimizer"):

        train_op = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

    # 5、计算准确率
    with tf.variable_scope("acc"):

        equal_list = tf.equal(tf.argmax(y_true, 1), tf.argmax(y_predict, 1))

        # equal_list  None个样本   [1, 0, 1, 0, 1, 1,..........]
        accuracy = tf.reduce_mean(tf.cast(equal_list, tf.float32))

    # 收集变量 单个数字值收集
    tf.summary.scalar("losses", loss)
    tf.summary.scalar("acc", accuracy)

    # 高纬度变量收集
    tf.summary.histogram("weightes", weight)
    tf.summary.histogram("biases", bias)

    # 定义一个初始化变量的op
    init_op = tf.global_variables_initializer()

    # 定义一个合并变量de op
    merged = tf.summary.merge_all()

    # 创建一个saver
    saver = tf.train.Saver()

    # 开启会话去训练
    with tf.Session() as sess:
        # 初始化变量
        sess.run(init_op)

        # 建立events文件，然后写入
        filewriter = tf.summary.FileWriter("./tmp/summary/test/", graph=sess.graph)

        if FLAGS.is_train == 1:
#         if 1 == 1:
            # 迭代步数去训练，更新参数预测
            for i in range(2000):

                # 取出真实存在的特征值和目标值
                mnist_x, mnist_y = mnist.train.next_batch(50)

                # 运行train_op训练
                sess.run(train_op, feed_dict={x: mnist_x, y_true: mnist_y})

                # 写入每步训练的值
                summary = sess.run(merged, feed_dict={x: mnist_x, y_true: mnist_y})

                filewriter.add_summary(summary, i)

                print("训练第%d步,准确率为:%f" % (i, sess.run(accuracy, feed_dict={x: mnist_x, y_true: mnist_y})))

            # 保存模型
            saver.save(sess, "./tmp/ckpt/fc_model")
        else:
            # 加载模型
            saver.restore(sess, "./tmp/ckpt/fc_model")

            # 如果是0，做出预测
            for i in range(100):

                # 每次测试一张图片 [0,0,0,0,0,1,0,0,0,0]
                x_test, y_test = mnist.test.next_batch(1)

                print("第%d张图片，手写数字图片目标是:%d, 预测结果是:%d" % (
                    i,
                    tf.argmax(y_test, 1).eval(),
                    tf.argmax(sess.run(y_predict, feed_dict={x: x_test, y_true: y_test}), 1).eval()
                ))
full_connected()